from __future__ import annotations

from typing import Any

from .results import ApplyResult, StepResult


WRITE_ACTIONS = {
    "create_destination",
    "apply_destination_settings",
    "apply_default_permissions",
    "configure_forum",
    "create_forum_topic",
    "apply_configuration_media",
}


async def apply_plan(plan: dict[str, Any], adapter: Any) -> ApplyResult:
    if plan.get("dry_run") is not True:
        raise ValueError("Expected a dry-run plan generated by TeleMorph.")
    if not plan.get("validation", {}).get("valid", False):
        raise ValueError("Cannot apply a plan with failed validation.")

    output = ApplyResult.empty()
    results: list[StepResult] = []
    destination: dict[str, Any] = {}

    for step in plan.get("steps", []):
        result = await apply_step(step, adapter)
        results.append(result)
        if step.get("id") == "create_destination" and result.status == "applied":
            destination = result.details

    return ApplyResult(
        generated_at=output.generated_at,
        destination=destination,
        results=results,
    )


async def apply_step(step: dict[str, Any], adapter: Any) -> StepResult:
    step_id = str(step.get("id") or "unknown")
    action = str(step.get("action") or "unknown")
    status = str(step.get("status") or "unknown")
    payload = step.get("payload", {})
    if not isinstance(payload, dict):
        payload = {}

    if status != "planned":
        return StepResult(
            step_id=step_id,
            action=action,
            status="skipped",
            message=f"Step status is {status}; only planned steps are applied.",
        )

    if action not in WRITE_ACTIONS:
        return StepResult(
            step_id=step_id,
            action=action,
            status="unsupported",
            message="No executor is registered for this action.",
        )

    handler = getattr(adapter, action, None)
    if handler is None:
        return StepResult(
            step_id=step_id,
            action=action,
            status="unsupported",
            message="Adapter does not implement this action.",
        )

    try:
        details = await handler(payload)
    except Exception as exc:
        return StepResult(
            step_id=step_id,
            action=action,
            status="failed",
            message=f"{type(exc).__name__}: {exc}",
        )

    result_status = (
        "failed"
        if details.get("failed") is True
        else "unsupported"
        if details.get("unsupported") is True
        else "skipped"
        if details.get("noop") is True
        else "applied"
    )
    result_message = (
        str(details.get("reason"))
        if result_status in {"unsupported", "skipped"} and details.get("reason")
        else "Step applied."
    )
    return StepResult(
        step_id=step_id,
        action=action,
        status=result_status,
        message=result_message,
        details=details if isinstance(details, dict) else {"result": details},
    )
